# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=50, verbose_name='\u041a\u043e\u043b\u0435\u043a\u0446\u0456\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043b\u0435\u043a\u0446\u0456\u044f',
                'verbose_name_plural': '\u041a\u043e\u043b\u0435\u043a\u0446\u0456\u044f',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50, verbose_name='\u041c\u043e\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0432\u0430',
                'verbose_name_plural': '\u041c\u043e\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Material')),
            ],
            options={
                'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0456\u0430\u043b',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.BooleanField(default=False, verbose_name=b'\xd0\x84 \xd1\x84\xd1\x80\xd0\xb0\xd0\xb3\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xbe\xd0\xbc')),
                ('compounds_amount', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name=b'\xd0\x9a\xd1\x96\xd0\xbb\xd1\x8c\xd0\xba\xd1\x96\xd1\x81\xd1\x82\xd1\x8c \xd1\x84\xd1\x80\xd0\xb0\xd0\xb3\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd1\x96\xd0\xb2')),
                ('collections', models.ManyToManyField(to='catalog.Collection', verbose_name='\u041a\u043e\u043b\u0435\u043a\u0446\u0456\u044f')),
                ('material', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='catalog.Material', verbose_name=b'\xd0\x9c\xd0\xb0\xd1\x82\xd0\xb5\xd1\x80\xd1\x96\xd0\xb0\xd0\xbb')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0434\u043c\u0435\u0442',
                'verbose_name_plural': '\u041f\u0440\u0435\u0434\u043c\u0435\u0442',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u043d\u044f')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Object', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0437\u0432\u0430',
                'verbose_name_plural': '\u041d\u0430\u0437\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Size_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f \u0432\u0438\u043c\u0456\u0440\u0443')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0432\u0438\u043c\u0456\u0440\u0443',
                'verbose_name_plural': '\u0422\u0438\u043f \u0432\u0438\u043c\u0456\u0440\u0443',
            },
        ),
        migrations.CreateModel(
            name='Size_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_unit', models.CharField(max_length=50, verbose_name='\u041e\u0434\u0438\u043d\u0438\u0446\u0456 \u0432\u0438\u043c\u0456\u0440\u0443')),
            ],
            options={
                'verbose_name': '\u041e\u0434\u0438\u043d\u0438\u0446\u0456 \u0432\u0438\u043c\u0456\u0440\u0443',
                'verbose_name_plural': '\u041e\u0434\u0438\u043d\u0438\u0446\u0456 \u0432\u0438\u043c\u0456\u0440\u0443',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Object', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442')),
                ('title_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Lang', verbose_name='\u041c\u043e\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0437\u0432\u0430',
                'verbose_name_plural': '\u041d\u0430\u0437\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Title_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f \u043d\u0430\u0437\u0432\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043d\u0430\u0437\u0432\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f \u043d\u0430\u0437\u0432\u0438',
            },
        ),
        migrations.AddField(
            model_name='title',
            name='title_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Title_type', verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Size_type', verbose_name='\u0422\u0438\u043f \u0432\u0438\u043c\u0456\u0440\u0443'),
        ),
        migrations.AddField(
            model_name='size',
            name='size_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Size_unit', verbose_name='\u041e\u0434\u0438\u043d\u0438\u0446\u0456 \u0432\u0438\u043c\u0456\u0440\u0443'),
        ),
    ]
